.TH pi 1 "date not needed" "too lazy to version" "User Commands"
.SH NAME
.B pi
\- prints digits of pi to stdout

.SH SYNOPSIS
.B pi
.RB [ \-flags ]
.RB [ \-\-option ]
.RI [ digits ]

.SH DESCRIPTION
Prints digits of pi to stdout.

.SH OPTIONS
.TP
.BR \-d ", " \-\-decimals
Prints only the decimals. Does not include the "3." at the start of pi.

.SH AUTHORS
.RI "Jenyyk / Rezyys / Jan Křivský: " "https://github.com/Jenyyk"

.SH LICENSE
Copyright (c) 2026 Jan Křivský. This program is licensed under the MIT License.

.SH BUGS
.RI "For bug reports please open an issue on github: " "https://github.com/Jenyyk/extrautils"
